language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nighthauk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nighthauk/docker-react yarn test